//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "config_info_aggr")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub data_id: String,
    pub group_id: String,
    pub datum_id: String,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub content: String,
    pub gmt_modified: DateTime,
    pub app_name: Option<String>,
    pub tenant_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
