//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "config_info_beta")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub data_id: String,
    pub group_id: String,
    pub app_name: Option<String>,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub content: String,
    pub beta_ips: Option<String>,
    pub md5: Option<String>,
    pub gmt_create: DateTime,
    pub gmt_modified: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub src_user: Option<String>,
    pub src_ip: Option<String>,
    pub tenant_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub encrypted_data_key: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
