//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "config_tags_relation")]
pub struct Model {
    pub id: i64,
    pub tag_name: String,
    pub tag_type: Option<String>,
    pub data_id: String,
    pub group_id: String,
    pub tenant_id: Option<String>,
    #[sea_orm(primary_key)]
    pub nid: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
