//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "config_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub data_id: String,
    pub group_id: Option<String>,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub content: Option<String>,
    pub md5: Option<String>,
    pub gmt_create: Option<DateTime>,
    pub gmt_modified: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub src_user: Option<String>,
    pub src_ip: Option<String>,
    pub app_name: Option<String>,
    pub tenant_id: Option<String>,
    pub c_desc: Option<String>,
    pub c_use: Option<String>,
    pub effect: Option<String>,
    pub r#type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub c_schema: Option<String>,
    pub encrypted_data_key: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
