//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::config_info::Entity as ConfigInfo;
pub use super::config_info_aggr::Entity as ConfigInfoAggr;
pub use super::config_info_beta::Entity as ConfigInfoBeta;
pub use super::config_info_tag::Entity as ConfigInfoTag;
pub use super::config_tags_relation::Entity as ConfigTagsRelation;
pub use super::group_capacity::Entity as GroupCapacity;
pub use super::his_config_info::Entity as HisConfigInfo;
pub use super::permissions::Entity as Permissions;
pub use super::roles::Entity as Roles;
pub use super::tenant_capacity::Entity as TenantCapacity;
pub use super::tenant_info::Entity as TenantInfo;
pub use super::users::Entity as Users;
