//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tenant_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub kp: String,
    pub tenant_id: Option<String>,
    pub tenant_name: Option<String>,
    pub tenant_desc: Option<String>,
    pub create_source: Option<String>,
    pub gmt_create: i64,
    pub gmt_modified: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
